### ISSUE TITLE
Needs a way to repeat answers

### ISSUE THREAD

**Issue by popey** [grifferz/pah-irc#10]
If the bot gets rate limited or some other glitch, sometimes all the answers don't appear.

Would be handy to have a command that only the tsar can execute which repeats all the answers.

**Comment by grifferz** [comment]
Okay. I can see that some sort of "plays" command would be useful, especially in a long-running game where the announcement may have happened a day or two before the Tsar noticed. So I will add a `plays` channel command.

Note that if it got rate-limited the first time then it probably will again, though.

**Comment by grifferz** [comment]
Should such a command be ignored as being "too soon", in the same way we are discussing for the `status` command in #6?

**Comment by popey** [comment]
Yes, anything publicly spamming the channel should be repeatable and limited. 

On the subject of it being rate-limited then perhaps the in-channel output from the bot should have the 0.5s delay it used to have, as they're longer pieces of text than the output in the pm. So the slowness of output in pm is frustrating to users, but slowly outputting the plays in-channel is less frustrating.

**Comment by grifferz** [comment]
> On the subject of it being rate-limited then perhaps the in-channel output from the bot should have the 0.5s delay it used to have

It will flood off or be silenced if it tries to send many messages at 0.5s interval.

You can tell this is the case because the problems were happening when it was listing off the plays that had been made. When it does that there is no private messaging going on. So just listing off the plays is enough, if the interval is short enough.

**Comment by Daviey** [comment]
Perhaps it should be in the public channel once, but anyone can run 'plays' in PM to refresh themselves on demand?

**Comment by grifferz** [comment]
I think there probably should be both, with rate-limiting for the public one.
