### ISSUE TITLE
"Ed Balls" house rule

### ISSUE THREAD

**Issue by tomgilder** [grifferz/pah-irc#109]
See below:

![6de77e3c-ce59-11e4-9e4b-bce190aa2b9b](https://cloud.githubusercontent.com/assets/756862/6765880/910bdbba-cfe9-11e4-9ee8-3aa713b430a6.jpg)

**Comment by grifferz** [comment]
So what would that actually do? Allow anyone to play "Ed Balls." as an answer any time? (What if two people played "Ed Balls"?)

**Comment by tomgilder** [comment]
It automatically tweets @edballsmp so he can decide who wins

**Comment by grifferz** [comment]
Am willing to consider it if anyone can confirm that @edballsmp is up for that.
