### ISSUE TITLE
Bot sends horizontal tab on status command

### ISSUE THREAD

**Issue by zuzak** [grifferz/pah-irc#114]
![Screenshot](http://img.prntscr.com/img?url=http://i.imgur.com/2Q2r3iz.png)

Bot [sends](https://github.com/grifferz/pah-irc/blob/37b118252552ba9b45227b66e728e272f6547137/lib/PAH.pm#L1015) a ^I halfway through a response when it probably shouldn't.

**Comment by grifferz** [comment]
Sorry, this was fixed in  https://github.com/grifferz/pah-irc/commit/7b010f6c90b6caf0f350afc2971fe8db90598fa7 but #debug is running an old version. Will restart it when I restart the one in #bitfolk.
