### ISSUE TITLE
Add a header and footer line around the list of plays

### ISSUE THREAD

**Issue by pidg** [grifferz/pah-irc#12]
This would make it easier to read and reduce impact on flood limit thing.

Perhaps add =================================== above and below the answers.

Optionally bot could also +m the channel for the duration of the answers to prevent breaks by users.

**Comment by grifferz** [comment]
Editing the title of this issue as the …or… has already been removed in issue #11.

**Comment by grifferz** [comment]
@pidg please can you submit the +m suggestion as a separate issue?

**Comment by grifferz** [comment]
Okay, let's give the header/footer thing a go.

**Comment by grifferz** [comment]
I don't know whether using colour codes could be acceptable also?

e.g. the entire Black Card text could be in one colour, the entire list of plays could be in another, or the plays could alternate colours to more easily distinguish one from another.

**Comment by grifferz** [comment]
Here you go.
-  `<AgainstDev>` grifferz: Which is the best play?
- `<AgainstDev>` =================================
- `<AgainstDev>` 1 → The Natural History Museum has just opened an interactive exhibit on **being on fire**.
- `<AgainstDev>` 2 → The Natural History Museum has just opened an interactive exhibit on **soup that is too hot**.
- `<AgainstDev>` 3 → The Natural History Museum has just opened an interactive exhibit on **the BNP**.
- `<AgainstDev>` =================================
