### ISSUE TITLE
Announce new Tsar when announcing the new Black Card in PM

### ISSUE THREAD

**Issue by zuzak** [grifferz/pah-irc#145]
At the culmination of a round, we announce the winner, the winning play, and the new Black Card in PM whilst simultaneously announcing the winner, the new Black Card and the new Tsar in the channel. We should probably make it announce the same things in each, so one doesn't have switch windows or issue commands to get the full story.

**Comment by grifferz** [comment]
I did not think that people cared that much who the Tsar was, but I suppose that some people want to play tactically and craft their play to the Tsar, so okay then. :)
