### ISSUE TITLE
Bot still thinks you're in multiple games even if all but one of them are inactive

### ISSUE THREAD

**Issue by jshholland** [grifferz/pah-irc#150]
After kicking the bot from a channel, it still seems to think there is a game taking place (at least for the play command; other ones seem to work properly-ish). The bot doesn't recognise quit commands sent over PM, so there is no way to leave the game without re-inviting the bot back to the channel and quitting there.

Related but possibly deserving of a separate issue is the question of whether the bot should auto-quit all players when it is kicked from a channel.

**Comment by grifferz** [comment]
Rather than allow resigning from private message, I think I would rather prevent any communication that it's doing after it's been kicked out of the channel. So, what messages has it been sending to people?

**Comment by jshholland** [comment]
It doesn't send any messages; the only reason I noticed was that I couldn't just do "4 2" to play in a different channel (which I thought would be the only one left on that network). It gave me the "Sorry, you're in multiple active games right now so I need you to specify which channel you mean." message.

**Comment by grifferz** [comment]
Okay, I think it would be better if I just made that part smarter then, so it knows you're only in one active game.

**Comment by grifferz** [comment]
This also seems to apply to the `hand` command.
