### ISSUE TITLE
New Black Card can be difficult to spot in a wall of text

### ISSUE THREAD

**Issue by grifferz** [grifferz/pah-irc#17]
A user commented that when the next Black Card is dealt it can be difficult to spot it in a wall of text. For example:

`<PAH>` The winner is **sarah**, who now has **9** Awesome Points!

`<PAH>` The new Card Tsar is **popey**.

`<PAH>` Time for the next Black Card:

`<PAH>` → Fun tip! When your man asks you to go down on him, try surprising him with _____ instead.

`<PAH>`Now message me your answers please!

A suggestion was made that perhaps the entire Black Card text should be presented in bold.

Any thoughts?

**Comment by grifferz** [comment]
I'm not sure that I would like to see the whole line bolded.

How about making the initial arrow (→) be bold and in, say, red?

**Comment by popey** [comment]
Personally I'd make the whole line bold. It's an important part of the game mechanic, so it should be easy to scroll back and see it among joins/parts/chatter.

**Comment by grifferz** [comment]
Okay, we'll give that a go.
