### ISSUE TITLE
Remaining players should be mentioned by bot

### ISSUE THREAD

**Issue by popey** [grifferz/pah-irc#24]
- `<PAH>` **dave2** has made their play! We're waiting on **2** more plays.

If number of players remaining is less than 3(?) it should name them

So..
- "We're waiting on 3 more players"
- "We're waiting on foo and bar"
- "We're waiting on foo"

**Comment by grifferz** [comment]
I'm gonna name-tag up to 5 people because there's room on an IRC line.

**Comment by grifferz** [comment]
@paul2d:
- `<grifferz>` Paul, so until I do the batching up with a timer thing, you wanted issue #24 reduced to 3?
- `<Paul>` grifferz: as a personal preference, yes. But I'm happy for you to consider 5 a better number :)

**Comment by grifferz** [comment]
Fixed by fix for #32
