### ISSUE TITLE
Bot should announce who is already in the game when gathering players

### ISSUE THREAD

**Issue by grifferz** [grifferz/pah-irc#26]
It's annoying that the bot doesn't say who is already in a game when someone new joins it, as it is easy to forget if you are already playing if it's been a while since the last turn:
- `<grifferz>` AgainstDev, status
- `<AgainstDev>` grifferz: A game exists but we only have **3** players. Find me **1** more and we're on.
- `<AgainstDev>` Any takers? Just type "AgainstDev: me" and you're in.

So am I already playing or what?!
- `<grifferz>` AgainstDev, dealmein
- `<AgainstDev>` grifferz: Heyyy, you're already playing!

fffffffuuuuuuuu!

If it had instead said…
- `<grifferz>` AgainstDev, status
- `<AgainstDev>` grifferz: A game exists but we only have **3** players: **you**, **bob** and **carol**. Find me **1** more and we're on.
- `<AgainstDev>` Any takers? Just type "AgainstDev: me" and you're in.

…then I'd have known.

On the other hand, perhaps the bot should avoid highlighting people who aren't required to take some sort of action?

**Comment by popey** [comment]
Highlighting people who are already in the game could motivate them to retire or poke non-players to play. However it could get old quickly if some random keeps asking for status.

**Comment by grifferz** [comment]
Good point. Perhaps if you're one of the players it could say:
- `<PAH>` grifferz: A game exists but we only have **3** players (including you). Find me **1** more and we're on.
- `<PAH>` Any takers? Just type "AgainstDev: me" and you're in.

or if you're not it could say:
- `<PAH>` grifferz: A game exists but we only have **3** players. Find me **1** more and we're on.
- `<PAH>` grifferz: How about you? Just type "AgainstDev: me" and you're in.

**Comment by popey** [comment]
Looks good to me.
