### ISSUE TITLE
Batch notifications of plays

### ISSUE THREAD

**Issue by dgl** [grifferz/pah-irc#32]
Rather than highlighting people in quick succession batch the `waiting on plays from ...` message and only send it once a minute.
- `200712 <PAH>` **foo** has made their play! We're currently waiting on plays from **3** people: **x**, **y** and **z**.
- `200712 <PAH>` **bar** has made their play! We're currently waiting on plays from **2** people: **y** and **z**.

This probably also means removing "foo" so it doesn't annoyingly highlight them a bit later about their own play.

e.g.:
- `200812 <PAH>` **2** people just played! We're currently waiting on plays from **2** people: **y** and **z**.

(i.e. a minute after the first message)

**Comment by grifferz** [comment]
This will also make #24 irrelevant.
