### ISSUE TITLE
Black card got stuck

### ISSUE THREAD

**Issue by dgl** [grifferz/pah-irc#34]
Edited IRC log:
- `<PAH>` The new Card Tsar is **player1**.
- `<PAH>` Time for the next Black Card:
- `<PAH>` → What did Vin Diesel eat for dinner?
- `<PAH>` Now message me your answers please!
- [snip]
- `<@player1` PAH, 4
- `<PAH>` The winner is **player2**, who now has **7** Awesome Points!
- `<PAH>` The new Card Tsar is **player3**.
- [...nothing...]
- `<player2>` urm
- `<player2>` PAH: status
- [snip]
- `<PAH>` Current Black Card:
- `<PAH>` → What did Vin Diesel eat for dinner?

**Comment by grifferz** [comment]
I see. It appears I forgot to check if there are any Black Cards left :)
