### ISSUE TITLE
Should be able to join a game with a completed hand

### ISSUE THREAD

**Issue by tolien** [grifferz/pah-irc#39]
When a hand is complete, new players can't join:

```
1353.41 <@Tolien> pah: me
1353.42 < PAH> tolien: Sorry, this hand is complete and we're waiting on taras to pick the winner. Please try again later.
```

I guess the alternative would be to add new players to a list then join them once the hand completes?

**Comment by grifferz** [comment]
Yep, I did think about this:

https://github.com/grifferz/pah-irc/blob/master/lib/PAH.pm#L907

:)

So yeah, could deal them in as soon as the next round starts.

**Comment by DeeHants** [comment]
+1 (I see no other way to vote for this)
