### ISSUE TITLE
1 minute batching of plays as implemented in #32 is maybe too short for slow games

### ISSUE THREAD

**Issue by grifferz** [grifferz/pah-irc#53]
- `<johnm>` Also, would it be possible to instead of messaging when someone plays, message updates once per minute for a few minutes, then reminding people every hour or so? then during busy times with big numbers of players it'll probably just go straight to the pick a winner step
- `<grifferz>` it sends a play notification one minute after a play is made and collects up all the plays made in that minute
- `<johnm>` grifferz: ah OK. :)
- `<plett>` grifferz: Maybe once per 10 minutes for the play notification would be better in the slow-play version? Or even longer?

**Comment by grifferz** [comment]
Original implementation was discussed in #32.

How about we try the play batching timer being 1/60th of the `turnclock` (minimum 60 seconds)? So #debug would remain at 60 seconds (`turnclock` is 3600 seconds), #bitfolk would become 24 minutes (86400 seconds divided by 60).

**Comment by plett** [comment]
Yes, setting it as a fraction of the turn timer sounds like a sensible thing to do.

**Comment by grifferz** [comment]
This seems to be working okay.
