### ISSUE TITLE
Add channel name for context in private messages

### ISSUE THREAD

**Issue by domcleal** [grifferz/pah-irc#57]
Private messages are missing the channel name for context when you're in more than one channel with PAH active.  You receive messages about receiving white cards, black cards being dealt etc without any indication of which hand it's being added to.

<pre>
090122 &lt;AgainstHumanity> 1 new White Card has been dealt to you:
090123 &lt;AgainstHumanity> → Scalping the Milkybar Kid.
090123 &lt;AgainstHumanity> To see your full hand, type "hand".
</pre>

It could also state that you need to type "#example hand" when in multi-channel mode.

**Comment by grifferz** [comment]
Ah. Good point. Yes I will do that.

Not much testing of multiple channels with the same players has taken place yet, so there will probably be more of this.

**Comment by grifferz** [comment]
Is it missing any channel context now?

**Comment by domcleal** [comment]
Not that I've noticed, thanks!
