### ISSUE TITLE
Status gets duplicated

### ISSUE THREAD

**Issue by popey** [grifferz/pah-irc#6]
If two people say "Pah status" in quick succession, it floods the irc channel with duplicate stuff...
- `<Paul>` pah status
- `<popey>` PAH status
- `<PAH>` Time for the next Black Card:
- `<PAH>` → What's that smell?
- `<PAH>` Now message me your answers please!
- `<PAH>` paul: A game is active! We're currently waiting on plays from **8** people: **paul**, **dave2**, **popey**, **sarah**, **tolien**, **dhaval2712**, **wizardged** and **rottnkorpse**.
- `<PAH>` The current Card Tsar is **dutchie**
- `<PAH>` Active Players: dutchie(6) dhaval2712(6) popey(5) dave2(4) sarah(4) paul(3) tolien(2) rottnkorpse(2) wizardged(0)
- `<PAH>` Top 3 all time: dutchie(6) dhaval2712(6) popey(5)
- `<RottNKorpse>` grifferz: stop oppressing us
- `<PAH>` Current Black Card:
- `<PAH>` → What's that smell?
- `<PAH>` popey: A game is active! We're currently waiting on plays from **8** people: **paul**, **dave2**, **popey**, **sarah**, **tolien**, **dhaval2712**, **wizardged** and **rottnkorpse**.
- `<PAH>` The current Card Tsar is **dutchie**
- `<PAH>` Active Players: dutchie(6) dhaval2712(6) popey(5) dave2(4) sarah(4) paul(3) tolien(2) rottnkorpse(2) wizardged(0)
- `<PAH>` Top 3 all time: dutchie(6) dhaval2712(6) popey(5)

**Comment by grifferz** [comment]
Would it be enough to not bother displaying the status if the status was asked for in the last minute, 2 minutes, 5 minutes or whatever?

**Comment by popey** [comment]
Yeah, I think it should ignore anything which results in in-channel output if it's been used within the last round. The problem occurs if someone is having a long game, disconnects then reconnects a day or so later and can't use the command because someone else did in this round. 

So yeah, a timer would be preferable.

**Comment by grifferz** [comment]
Let's go with 2 minutes to begin with.

**Comment by grifferz** [comment]
Have to say that during testing I am finding 2 minutes to be quite irritating. But perhaps in real play people will need to use `status` less.
