### ISSUE TITLE
"status" command should have a clock

### ISSUE THREAD

**Issue by zuzak** [grifferz/pah-irc#66]
It'd be nice to know how long each round has gone on for, and how long it will be before people are forcibly resigned.

**Comment by grifferz** [comment]
The start time of the round isn't currently stored, but that could be added.

I wonder where to add the text.

Current text:
- `<AgainstHumanity>` A game is active in **#bitfolk**! We're currently waiting on the Card Tsar (**dave2**) to pick a winner.
- `<AgainstHumanity>` The current Card Tsar in **#bitfolk** is dave2
- `<AgainstHumanity>` Active Players in **#bitfolk**: grifferz(2) zuzak(1) ziphy(1) popey(1) dave2(1) dominic(0) tolien(0) tommy(0) dutchie(0) plett(0) daviey(0) 
- `                  prando(0) dg(0) filbert(0) paul(0) ging(0) robert(0) dotwaffle(0)
- `<AgainstHumanity>` Top 3 all time in **#bitfolk**: grifferz(2) zuzak(1) ziphy(1) popey(1) dave2(1)
- `<AgainstHumanity>` Current Black Card in **#bitfolk**:
- `<AgainstHumanity>` → **The school trip was completely ruined by _____.**

The fact that a game is active is perhaps implied, so maybe lose that and add it on the end of the first line? e.g.:
- `<AgainstHumanity>` Waiting on the Card Tsar (**dave2**) to pick a winner. Round started about **18 hrs, 20 mins ago**. Idle punishment in about **22 hrs, 50 mins**.
- `<AgainstHumanity>` The current Card Tsar in **#bitfolk** is dave2
- `<AgainstHumanity>` Active Players in **#bitfolk**: grifferz(2) zuzak(1) ziphy(1) popey(1) dave2(1) dominic(0) tolien(0) tommy(0) dutchie(0) plett(0) daviey(0) prando(0) dg(0) filbert(0) paul(0) ging(0) robert(0) dotwaffle(0)
- `<AgainstHumanity>` Top 3 all time in **#bitfolk**: grifferz(2) zuzak(1) ziphy(1) popey(1) dave2(1)
- `<AgainstHumanity>` Current Black Card in **#bitfolk**:
- `<AgainstHumanity>` → **The school trip was completely ruined by _____.**

I think I'd prefer friendly time deltas (6 hrs, 20 mins ago; 22 hrs, 50 mins) than absolute time stamps. Thoughts?

**Comment by domcleal** [comment]
:+1: suggested output looks good.
