### ISSUE TITLE
New white card not dealt after winning hand

### ISSUE THREAD

**Issue by domcleal** [grifferz/pah-irc#68]
I joined a round yesterday in #bitfolk, and was dealt ten cards, one of which I played:

<pre>
170331 &lt;AgainstHumanity&gt; 10 new White Cards have been dealt to you in #bitfolk:
...
170336 &lt;AgainstHumanity&gt;  6. Scalping the Milkybar Kid.
...
170339 &lt;AgainstHumanity&gt; Current Black Card:
170340 &lt;AgainstHumanity&gt; → The school trip was completely ruined by _____.
170421 &lt;Dominic&gt; #bitfolk play 6
170421 &lt;AgainstHumanity&gt; Thanks. So this is your play for #bitfolk:
170422 &lt;AgainstHumanity&gt; → The school trip was completely ruined by scalping the Milkybar Kid.
</pre>

The card won:

<pre>
113702 &lt;@Dave2&gt; AgainstHumanity, 9
113722 &lt; AgainstHumanity&gt; The winner is dominic, who now has 1 Awesome Point! The new Card Tsar is dutchie. Time for the next Black Card:
113746 &lt; AgainstHumanity&gt; → Why do I hurt all over?
</pre>

But the only message I received from PAH was informing me about the new black card.  Checking my hand again, I see the same card (6) is present and I didn't receive a new white card.

<pre>
113726 &lt;AgainstHumanity&gt; Time for the next Black Card in #bitfolk:
113726 &lt;AgainstHumanity&gt; → Why do I hurt all over?
115818 &lt;Dominic&gt; #bitfolk hand
115818 &lt;AgainstHumanity&gt; Your White Cards in #bitfolk:
...
115822 &lt;AgainstHumanity&gt;  6. Scalping the Milkybar Kid.
...
</pre>

**Comment by grifferz** [comment]
Yeah in that round only 8 people got their played card discarded. I don't know why yet. :(

**Comment by grifferz** [comment]
I botched the implementation of #63 and I think that was what was responsible for this. I hope my fixes for #63 today also take care of this.

**Comment by grifferz** [comment]
I'm satisfied that this was fixed by  6d9dcc9.
