### ISSUE TITLE
48 hour warning shouldn't be hardcoded

### ISSUE THREAD

**Issue by zuzak** [grifferz/pah-irc#76]
The bot [says](https://github.com/grifferz/pah-irc/blob/99735fbe523afb08ea6e58d5249886c373758ebc/lib/PAH.pm#L1736) that "turns in this game can take up to 48 hours" regardless of how long `turnclock` is set to. When a round actually takes an hour (for example, `#debug`), this statement is rather misleading.

**Comment by grifferz** [comment]
True. I think the maximum would be about twice the turnclock, as the bot will start resigning players every minute after the turnclock has expired until the hand is complete. Then it resets the turnclock, and if it expires again it will resign the Tsar.

So I'll change the message to be twice the turnclock.
