### ISSUE TITLE
Answers ending with punctuation should not have . appended

### ISSUE THREAD

**Issue by pidg** [grifferz/pah-irc#8]
`<PAH>` 6 → What will always get you laid? **Surprise sex!**.

**Comment by pidg** [comment]
Same goes for questions like

`<PAH>` Time for the next Black Card:

`<PAH>` → Step 1: _____.

`<PAH>` → Step 2: _____.

`<PAH>` → Step 3: Profit.

**Comment by zuzak** [comment]
This is still a problem, e.g.
`11:35:47 <+P_A_H> 5 → What did I bring back from Amsterdam? Surprise sex!.`

**Comment by grifferz** [comment]
Having difficulty replicating this one…
- `18:43:13 <+AgainstDev>` 3 → On the third day of Christmas, my true love gave to me: three French hens, two turtle doves and **surprise sex!**

Will try with that same Black Card as well.

**Comment by grifferz** [comment]
Yeah that does it. Must be the existence of the question mark.
- 18:47:36 `<AgainstDev>` Thanks. So this is your play for **#ah**:
- 18:47:37 `<AgainstDev>` → What did I bring back from Amsterdam? **Surprise sex!.**

**Comment by grifferz** [comment]
Okay, it wasn't the question mark. Black Cards with zero blanks were going through a code path that mistakenly did not fix the punctuation.
