### ISSUE TITLE
Asking for one's hand whilst paused is weird

### ISSUE THREAD

**Issue by zuzak** [grifferz/pah-irc#81]
It doesn't actually show me my hand when the game is paused, but it thinks it does:

```
13:47:22 <zuzak> hand
13:47:22 <PAH> Your White Cards in #debug:
```

Side thought: maybe instead of pausing the game, it should just prolong the round indefinitely (never reaching the "which hand is best?" section until quorum is reached)

**Comment by grifferz** [comment]
I can't seem to replicate this at the moment so I may have inadvertently fixed it while working on something else.

I've tried requesting `hand` while the game is paused, and it seems to do it okay. I tried when I was resigned and it correctly said I wasn't playing.

So I think it's no longer an issue, but let me know if you still can reproduce it…

**Comment by grifferz** [comment]
Seems to have been fixed.
