### ISSUE TITLE
Bot sometimes says "0 people recently played…" or wrong number of people played

### ISSUE THREAD

**Issue by grifferz** [grifferz/pah-irc#89]
- `<AgainstHumanity>` **0** people recently played! We're currently waiting on plays from **4** more people.

I've been able to replicate it by making a play and then doing another play immediately.

**Comment by domcleal** [comment]
Related:
- `<+AgainstHumanity>` 8 people recently played! We're currently waiting on plays from 7 more people.
- `<+AgainstHumanity>` 1 person recently played! We're currently waiting on plays from 5 more people.
- `<@Dominic>` huh, seven minus one is five?
- `<@grifferz>` we already know there's soemthing wrong with that count when the same person plays twice within the time period, so it might be that
- `<@grifferz>` yes, Dee played twice within 22 seconds
